# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\change_mode.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, 修改模式):
        修改模式.setObjectName("修改模式")
        修改模式.setGeometry(QtCore.QRect(0, 0, 259, 340))
        self.verticalLayoutWidget = QtWidgets.QWidget(修改模式)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 241, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.verticalLayoutWidget)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(修改模式)
        self.buttonBox.accepted.connect(修改模式.accept) # type: ignore
        self.buttonBox.rejected.connect(修改模式.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(修改模式)

    def retranslateUi(self, 修改模式):
        _translate = QtCore.QCoreApplication.translate
        修改模式.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "TextLabel"))
