# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\.ui\dialog_mode_change.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modechange(object):
    def setupUi(self, modechange):
        modechange.setObjectName("modechange")
        modechange.resize(314, 257)
        self.label = QtWidgets.QLabel(modechange)
        self.label.setGeometry(QtCore.QRect(30, 40, 221, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setObjectName("label")
        self.buttonBox = QtWidgets.QDialogButtonBox(modechange)
        self.buttonBox.setGeometry(QtCore.QRect(90, 200, 217, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.retranslateUi(modechange)
        QtCore.QMetaObject.connectSlotsByName(modechange)

    def retranslateUi(self, modechange):
        _translate = QtCore.QCoreApplication.translate
        modechange.setWindowTitle(_translate("modechange", "Dialog"))
        self.label.setText(_translate("modechange", "TextLabel"))
